### ISSUE TITLE
run on google colab

### ISSUE THREAD

**Issue by mh-mahmoud** [Arthur151/CenterHMR#13]
Hi, 
thanks for releasing the code. 
When I run the code on the google colab, I get this error 

----------------
Configuration:
{'tab': 'test', 'configs_yml': 'configs/basic_test.yml', 'demo_image_folder': 'None', 'multi_person': True, 'use_coordmaps': True, 'head_conv_block_num': 2, 'kp3d_format': 'smpl24', 'eval': False, 'max_person': 16, 'BN_type': 'BN', 'Rot_type': '6D', 'center_idx': 1, 'centermap_size': 64, 'HMloss_type': 'MSE', 'model_precision': 'fp32', 'baseline': 'hrnetv5', 'input_size': 512, 'gmodel_path': '../trained_models/pw3d_81.8_58.6.pkl', 'best_save_path': '', 'print_freq': 50, 'epoch': 300, 'fine_tune': True, 'lr': 0.0003, 'weight_decay': 1e-05, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 2, 'nw': 4, 'dataset_rootdir': '/content/dataset/', 'dataset': 'h36m,mpii,coco,aich,up,ochuman,lsp,movi', 'voc_dir': '/content/dataset/VOCdevkit/VOC2012/', 'high_resolution': True, 'save_best_folder': '/content/checkpoints/', 'log_path': '/content/log/', 'total_param_count': 85, 'smpl_model_path': '/content/CenterHMR/models', 'adjust_lr_epoch': [], 'kernel_sizes': [5], 'GPUS': 0, 'save_mesh': False, 'save_centermap': True, 'save_dict_results': True, 'webcam': False, 'multiprocess': False}
----------------
pygame 2.0.0 (SDL 2.0.12, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
model_type smpl
start building model.
********************
using fine_tune model:  ../trained_models/pw3d_81.8_58.6.pkl
missing parameters of layers:
[]
********************
finished build model.
Initialization finished!
gathering datasets
Loading 3 internet data from:/content/CenterHMR/demo/images
Size should be int or sequence. Got <class 'numpy.ndarray'>
Size should be int or sequence. Got <class 'numpy.ndarray'>
Traceback (most recent call last):
  File "core/test.py", line 194, in <module>
    main()
  File "core/test.py", line 190, in main
    demo.run(demo_image_folder)
  File "core/test.py", line 28, in run
    for test_iter,data_3d in enumerate(loader_val):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/content/CenterHMR/src/dataset/internet.py", line 84, in __getitem__
    return self.get_item_single_frame(index)
  File "/content/CenterHMR/src/dataset/internet.py", line 43, in get_item_single_frame
    torchvision.transforms.Resize(resized_image_size, interpolation=3),
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 253, in __init__
    raise TypeError("Size should be int or sequence. Got {}".format(type(size)))
TypeError: Size should be int or sequence. Got <class 'numpy.ndarray'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/CenterHMR/src/dataset/mixed_dataset.py", line 19, in __getitem__
    return self.dataset[index]
  File "/content/CenterHMR/src/dataset/internet.py", line 88, in __getitem__
    return self.get_item_single_frame(index)
  File "/content/CenterHMR/src/dataset/internet.py", line 43, in get_item_single_frame
    torchvision.transforms.Resize(resized_image_size, interpolation=3),
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 253, in __init__
    raise TypeError("Size should be int or sequence. Got {}".format(type(size)))
TypeError: Size should be int or sequence. Got <class 'numpy.ndarray'>

**Comment by Arthur151** [comment]
Sorry for the unpleasant bugs. We have fixed it. Please reload the colab. It should be fine now.
Feel free to conntect me if there are any bugs. Have a good time

**Comment by Arthur151** [comment]
I will close this issue if there is no further bug report.
