### ISSUE TITLE
Can't run demo with provided instructions

### ISSUE THREAD

**Issue by jbohnslav** [Arthur151/CenterHMR#2]
Hi there,

Really awesome work. Unfortunately, it can't run with the provided instructions. Trying to `sh run.sh` results in multiple errors. 

First: 
```
----------------
Traceback (most recent call last):
  File "core/test.py", line 2, in <module>
    from base import *
  File "/home/jb/Documents/python/CenterHMR/src/core/base.py", line 20, in <module>
    from dataset.mixed_dataset import SingleDataset
  File "/home/jb/Documents/python/CenterHMR/src/dataset/mixed_dataset.py", line 5, in <module>
    from dataset.internet import Internet
  File "/home/jb/Documents/python/CenterHMR/src/dataset/internet.py", line 9, in <module>
    import smplx
ModuleNotFoundError: No module named 'smplx'
```
I installed smplx from here: https://github.com/vchoutas/smplx

Next: 
```
----------------
In Ubuntu, using osmesa mode for rendering
Traceback (most recent call last):
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/osmesa.py", line 25, in GL
    mode=ctypes.RTLD_GLOBAL 
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('OSMesa: cannot open shared object file: No such file or directory', 'OSMesa', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core/test.py", line 2, in <module>
    from base import *
  File "/home/jb/Documents/python/CenterHMR/src/core/base.py", line 21, in <module>
    from visualization.visualization import Visualizer
  File "/home/jb/Documents/python/CenterHMR/src/visualization/visualization.py", line 15, in <module>
    from .renderer import get_renderer
  File "/home/jb/Documents/python/CenterHMR/src/visualization/renderer.py", line 19, in <module>
    import pyrender
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/osmesa.py", line 66, in GetCurrentContext
    function = self.OSMesa.OSMesaGetCurrentContext
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/osmesa.py", line 60, in OSMesa
    def OSMesa( self ): return self.GL
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/platform/osmesa.py", line 28, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'OSMesa: cannot open shared object file: No such file or directory', 'OSMesa', None)
```

I had to install Mesa using the instructions from PyRender: https://pyrender.readthedocs.io/en/latest/install/

Next: 
```
Traceback (most recent call last):
  File "core/test.py", line 50, in <module>
    main()
  File "core/test.py", line 46, in main
    demo.run(demo_image_folder)
  File "core/test.py", line 20, in run
    self.visualizer = Visualizer(model_type=self.model_type,resolution =vis_size, input_size=self.input_size, result_img_dir = test_save_dir,with_renderer=True)
  File "/home/jb/Documents/python/CenterHMR/src/visualization/visualization.py", line 23, in __init__
    self.renderer = get_renderer(model_type=model_type,resolution=self.resolution)
  File "/home/jb/Documents/python/CenterHMR/src/visualization/renderer.py", line 138, in get_renderer
    renderer = Renderer(faces,resolution=resolution[:2])
  File "/home/jb/Documents/python/CenterHMR/src/visualization/renderer.py", line 69, in __init__
    point_size=1.0)
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/pyrender/platforms/osmesa.py", line 19, in init_context
    from OpenGL.osmesa import (
ImportError: cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa' (/home/jb/anaconda3/envs/centerhmr/lib/python3.7/site-packages/OpenGL/osmesa/__init__.py)
```

This one stumped me, couldn't get it to work. Maybe my Mesa installation is still not correct?

**Comment by Arthur151** [comment]
Sorry for the unpleasant bugs. Please refer to the latest commit. We have change the render imgine for ubuntu to :
`'''
if 'Ubuntu' in platform.version():
    print('In Ubuntu, using osmesa mode for rendering')
    os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
else:
    print('In other system, using egl mode for rendering')
    os.environ['PYOPENGL_PLATFORM'] = 'egl'
'''
os.environ['PYOPENGL_PLATFORM'] = 'egl'`

**Comment by Arthur151** [comment]
Please let me know if there are any bugs. Besides, we have removed the reliance on the remarkable smplx. Please just uncomment the `import smplx` to fix the related bugs.

**Comment by Arthur151** [comment]
Closed without furthur response.

**Comment by jbohnslav** [comment]
Been a bit busy, but just tried it out. Works great now! Thanks for the quick response.

**Comment by Robisses** [comment]
Hello, I encountered the same problem as you, but mine cannot be solved, how did you solve it in the end?

>

**Comment by Robisses** [comment]
![问题](https://user-images.githubusercontent.com/43957014/110191417-4508d180-7e63-11eb-94f5-ec0607ef7b11.png)
Sorry, I forget to upload the picture.  This is my problem.

**Comment by Arthur151** [comment]
Please try to simply use :
`os.environ['PYOPENGL_PLATFORM'] = 'egl'`
like [this](https://github.com/Arthur151/CenterHMR/blob/d3eaec03b890a2a8728c0303f151ba1afc0f5a50/src/visualization/renderer.py#L19).

**Comment by Robisses** [comment]
Thank you for your quickly reply! But I'm trying to run this code in Ubuntu, and when I use "os.environ['PYOPENGL_PLATFORM'] = 'egl'" it will cause another problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu Sun"<notifications@github.com&gt;; 
发送时间: 2021年3月6日(星期六) 上午10:11
收件人: "Arthur151/CenterHMR"<CenterHMR@noreply.github.com&gt;; 
抄送: "2277494890"<2277494890@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Arthur151/CenterHMR] Can&#39;t run demo with provided instructions (#2)





 
Please try to simply use :
 os.environ['PYOPENGL_PLATFORM'] = 'egl'
 like this.

**Comment by littlejiumi** [comment]
Traceback (most recent call last):
  File "/root/Downloads/SPIN/demo.py", line 115, in <module>
    renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl.faces)
  File "/root/Downloads/SPIN/utils/renderer.py", line 16, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=img_res,
  File "/root/anaconda3/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/root/anaconda3/lib/python3.9/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/root/anaconda3/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 186, in init_context
    self._egl_context = eglCreateContext(
  File "/root/anaconda3/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/root/anaconda3/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
	err = 12297,
	baseOperation = eglCreateContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f340cd11340>,
		<OpenGL._opaque.EGLConfig_pointer object at 0x7f340cd113c0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f340ccdab40>,
		<OpenGL.arrays.lists.c_int_Array_7 object at 0x7f340cd114c0>,
	),
	result = <OpenGL._opaque.EGLContext_pointer object at 0x7f340cd11b40>
)

"egl' cause this...

**Comment by Arthur151** [comment]
Oh, this seems to be the bug of SPIN. Please consider to ask the authors of SPIN.

**Comment by jinfagang** [comment]
@Arthur151 switch to egl still get error:

```
romp/utils/visualization/renderer_pyrd.py", line 79, in __call__
    color, rend_depth = self.renderer.render(scene, flags=pyrender.RenderFlags.RGBA)
  File "/root/anaconda3/lib/python3.9/site-packages/pyrender/offscreen.py", line 86, in render
    self._platform.make_current()
  File "/root/anaconda3/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 196, in make_current
    assert eglMakeCurrent(
  File "/root/anaconda3/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fb02cb8d7c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fb0358165c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fb0358165c0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fb02cb8d2c0>,
        ),
        result = 0
)
```

**Comment by Arthur151** [comment]
Hi, Jin Tian,
Thanks for your interests in ROMP! I am running ROMP on a centos server too. This Pyrender bug is a tough one. To avoid getting trapped by this bug, latest version of ROMP supports using pytorch3D for rendering. Just switch it to pytorch3D in [this config](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/configs/image.yml#L16). It is much easier to [install](https://github.com/Arthur151/ROMP/blob/master/docs/installation.md). 
Feel free to post the bug you meet here. I will response in time.
Best,
Yu

**Comment by jinfagang** [comment]
@Arthur151 I swithed to pytorch3d and now it render on centos. 
pyrender is really buggy, I directly read model file from pkl it can render, but runs on video it can not.. don't know why.

**Comment by Arthur151** [comment]
Glad to hear that pytorch3d works. I have been confused by pyrender too much times, so do the other developers. I am not a rendering guy. So I can only find some alternative stuff, like maintaining a stable version of pytorch3d. 
At my service and keep watching, sir~

**Comment by jinfagang** [comment]
@Arthur151 BTW, if I  set stand on image vis to True, the code coredumped. Do u know why?

**Comment by Arthur151** [comment]
Yes, I do know why. 
Sadly speaking that a server doesn't support (lack some hardwares I guess) the rendering with vtk-tools, like vedo that I use to achieve stand on image vis. So stand on image vis can only run on a desktop with.

**Comment by jinfagang** [comment]
@Arthur151 Also , seems pytorch3d some op doesn't support fp16? Like Meshes class:

```
File "/root/anaconda3/lib/python3.9/site-packages/pytorch3d/transforms/transform3d.py", line 753, in _broadcast_bmm
    return a.bmm(b)
RuntimeError: expected scalar type Half but found Float
```

**Comment by Arthur151** [comment]
Yes, fp16 is some kind of high-level operations. The pytorch3d guies are still busy with implementing some basic function. They may support such high-level operations in the future.

**Comment by jinfagang** [comment]
@Arthur151 Hi, wanna ask you a question. Do u know how to show video frame by frame but also in vedo with interactive mode on?

Something like I can switch the camera angle while predict realtime on videos.
