### ISSUE TITLE
Can't run demo on Google Colab

### ISSUE THREAD

**Issue by PiotrMi** [Arthur151/CenterHMR#5]
Colab notebook: [https://colab.research.google.com/drive/18Y9-cLJftQZMi45YS7vHFf6-cyoQrFV-?usp=sharing](https://colab.research.google.com/drive/18Y9-cLJftQZMi45YS7vHFf6-cyoQrFV-?usp=sharing)

Used Google Colab GPU runtime.
Also had to edit config.py because the config file path string kept getting corrupted.

Error when running run.sh:

```
/content/CenterHMR/src
: not found
: not found
cat: 'configs/basic_test.yml'$'\r': No such file or directory
Error: invalid path 'ARGS.GPUS', can't query subvalue 'ARGS' of a leaf (leaf value is None).
Namespace(BN_type='BN', HMloss_type='MSE', Rot_type='6D', baseline='hrnetv4', batch_size=64, best_save_path='', center_idx=1, centermap_size=64, configs_yml='configs/basic_test.yml\r', dataset='h36m,mpii,coco,aich,up,ochuman,lsp,movi', dataset_rootdir='/content/dataset/', demo_image_folder='None', epoch=300, eval=False, fine_tune=False, gmodel_path='', gpu='\r', head_conv_block_num=2, high_resolution=True, input_size=512, kp3d_format='smpl24', log_path='/content/log/', lr=0.0003, max_person=16, model_precision='fp32', multi_person=True, nw=4, print_freq=50, save_best_folder='/content/checkpoints/', smpl_model_path='/content/CenterHMR/models', tab='CenterHMR', total_param_count=85, use_coordmaps=True, val_batch_size=64, voc_dir='/content/dataset/VOCdevkit/VOC2012/', weight_decay=1e-05)
Namespace(BN_type='BN', HMloss_type='MSE', Rot_type='6D', baseline='hrnetv4', batch_size=64, best_save_path='', center_idx=1, centermap_size=64, configs_yml='configs/basic_test.yml', dataset='h36m,mpii,coco,aich,up,ochuman,lsp,movi', dataset_rootdir='/content/dataset/', demo_image_folder='None', epoch=300, eval=False, fine_tune=False, gmodel_path='', gpu='\r', head_conv_block_num=2, high_resolution=True, input_size=512, kp3d_format='smpl24', log_path='/content/log/', lr=0.0003, max_person=16, model_precision='fp32', multi_person=True, nw=4, print_freq=50, save_best_folder='/content/checkpoints/', smpl_model_path='/content/CenterHMR/models', tab='CenterHMR', total_param_count=85, use_coordmaps=True, val_batch_size=64, voc_dir='/content/dataset/VOCdevkit/VOC2012/', weight_decay=1e-05)
----------------
Configuration:
{'tab': 'test', 'configs_yml': 'configs/basic_test.yml', 'demo_image_folder': '/content/CenterHMR/demo/images', 'multi_person': True, 'use_coordmaps': True, 'head_conv_block_num': 2, 'kp3d_format': 'smpl24', 'eval': False, 'max_person': 16, 'BN_type': 'BN', 'Rot_type': '6D', 'center_idx': 1, 'centermap_size': 64, 'HMloss_type': 'MSE', 'model_precision': 'fp32', 'baseline': 'hrnetv5', 'input_size': 512, 'gmodel_path': '../trained_models/pw3d_81.8_58.6.pkl', 'best_save_path': '', 'print_freq': 50, 'epoch': 300, 'fine_tune': True, 'lr': 0.0003, 'weight_decay': 1e-05, 'gpu': '\r', 'batch_size': 64, 'val_batch_size': 2, 'nw': 4, 'dataset_rootdir': '/content/dataset/', 'dataset': 'h36m,mpii,coco,aich,up,ochuman,lsp,movi', 'voc_dir': '/content/dataset/VOCdevkit/VOC2012/', 'high_resolution': True, 'save_best_folder': '/content/checkpoints/', 'log_path': '/content/log/', 'total_param_count': 85, 'smpl_model_path': '/content/CenterHMR/models', 'adjust_lr_epoch': [], 'kernel_sizes': [5], 'GPUS': 0, 'save_mesh': False, 'save_centermap': False}
----------------
model_type smpl
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "core/test.py", line 50, in <module>
    main()
  File "core/test.py", line 41, in main
    demo = Demo()
  File "core/test.py", line 7, in __init__
    self.set_up_smplx()
  File "/content/CenterHMR/src/core/base.py", line 53, in set_up_smplx
    self.smplx = smpl_mdoel.create(args.smpl_model_path, batch_size=self.batch_size,model_type=self.model_type, gender='neutral', use_face_contour=False, ext='npz', joint_mapper=joint_mapper,flat_hand_mean=True, use_pca=False).cuda()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 397, in _apply
    self._buffers[key] = fn(buf)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 190, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47
```

**Comment by Arthur151** [comment]
Bug fixed! Thanks for your interest! 
Have a nice time
